version: "3"

services:
  gemini-telegram-bot:
    environment:
      - MONGODB_PORT=${MONGODB_PORT:-27017}
      - MONGODB_NAME=${MONGODB_NAME:-gemini-telegram-bot}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN:?error}
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY:?error}
      - ALLOWED_TELEGRAM_USERNAMES=${ALLOWED_TELEGRAM_USERNAMES}
      - CHAT_HISTORY_LIMIT=${CHAT_HISTORY_LIMIT:-10}
      - DEVELOPER_CHAT_ID=${DEVELOPER_CHAT_ID}
    restart: always
    build:
      context: "."
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - ${MONGODB_PORT:-27017}:27017
    volumes:
      - ${MONGODB_PATH:-./mongodb}:/data/db
    # TODO: add auth

  mongo_express:
    image: mongo-express:latest
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT:-8081}:${MONGO_EXPRESS_PORT:-8081}
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=${MONGODB_PORT:-27017}
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=${MONGODB_NAME:-gemini-telegram-bot}
      - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_USERNAME:-username}
      - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_PASSWORD:-password}
    depends_on:
      - mongo
